config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'gossips#index'
  resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

def index
	@gossips=Gossip.all
end

def new
	@gossip=Gossip.new
end

def show
	@gossip=Gossip.find(params[:id])
end

def create
	@gossip=Gossip.new(gossip_params)
	if @gossip.save
		redirect_to gossip_path(@gossip)
	else
		render "new"
	end
end
def edit
	@gossip=Gossip.find(params[:id])
end

 def update
  	@gossip = Gossip.find(params[:id])
  	new_gossip = gossip_params
  	if @gossip.update(new_gossip)
  	  redirect_to gossip_path(@gossip)
  	else
  	  render 'edit'
  	end
  end
 def destroy
  	@gossip = Gossip.find(params[:id])
  	@gossip.destroy
  	redirect_to gossips_path
 end




private
  def gossip_params
  	params.require(:gossip).permit(:anonymous_author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gossips/edit.html.erb
<link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
<h1>Edition du gossip</h1>
<br/>
<%= form_for @gossip do |g| %>
	<div class='form-group'>
		<label>Autheur</label>
		<%= g.text_field :anonymous_author, class: 'form-control' %>
	</div>
	<div class='form-group'>
		<label>Contenu du gossip</label>
		<%= g.text_field :content, class: 'form-control' %>
	</div>
	<br/>
	<div class='form-group'>
		<button type='submit' class='btn btn-primary'>Editer le gossip</button>
		
	</div>
	<div class='form-group'>
		<a href='<%= gossip_path(@gossip.id) %>' class='btn btn-danger' data-confirm='Etes vous sur?' data-method='DELETE'>Supprimer</a>
	</div>
<%end%>

app/views/gossips/index.html.erb
<link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
<h1> Voici la liste des gossips ! </h1>

<% @gossips.each do |gossip| %>
<h2><%= gossip.anonymous_author %> </h2>
<p><%= gossip.content %> </p>
<p>
		<a href='<%= gossip_path(gossip.id) %>' class='btn btn-primary'>Lire la suite</a>
		<a href='<%= edit_gossip_path(gossip.id) %>' class='btn btn-warning'>Editer</a>
		<a href='<%= gossip_path(gossip.id) %>' class='btn btn-danger' data-confirm='Etes vous sur?' data-method='DELETE'>Supprimer</a>
</p> 
<% end %>
<br/>
<p> <a href='<%= new_gossip_path %>' class='btn btn-primary'>Créer un nouveau gossip</a> </p>

app/views/gossips/new.html.erb
<h1> Balance ton dossier mon pote  <i class="em em-face_with_finger_covering_closed_lips"></i></h1> 
<%= form_for @gossip do |g| %>
	<div class="form-group">
		<label>Auteur Anonyme</label>
		<%= g.text_field :anonymous_author, class:'form-control' %>
	</div>
	<div class="form-group">
		<label>Ce que tu as à raconter</label>
		<%= g.text_field :content ,class:'form-control' %>
	</div>
	<div class="form-group">
		<button type='submit' class='btn btn-primary'>Poster le gossip</button>
	</div>
<% end %>
<br/> <br/> 
<p><a href="<%=gossips_path%>" class='btn btn-primary'>Retour à la liste</a></p>

app/views/gossips/show.html.erb
<h1> <%= @gossip.anonymous_author %> </h1>

<p> <%= @gossip.content %></p>

</br>

<p>
	<a href="<%=gossips_path%>" class='btn btn-primary'>Retour à la liste</a>
	<a href="<%=edit_gossip_path%>" class='btn btn-default'>Modifier ce gossip</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
  <link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>